import productImage from '../../assests/img/foto-product.jpg'

export const categoryAndProducts = [
  {
    idApartment: 0,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 1,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 2,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 3,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 4,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 5,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 6,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 7,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 8,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 9,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Quilicura",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 10,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Renca",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 11,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Renca",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 12,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Renca",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 13,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Renca",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
];
