import productImage from '../../assests/img/foto-product.jpg';
import productImage2 from '../../assests/img/pruduct2.jpg';
import productImage3 from '../../assests/img/product3.jpg';
import productImage4 from '../../assests/img/product4.jpg';
import productImage5 from '../../assests/img/product5.jpg';

export const categoryAndProducts = [
  {
    idApartment: 0,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 1,
    bedRooms: 1,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 1,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 1,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 2,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 1,
    bedRooms: 3,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 3,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 1,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 4,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 5,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 1,
    bedRooms: 4,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 6,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 7,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 8,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 2,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 9,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 10,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 11,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 6,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 12,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 13,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 14,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 15,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 16,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 17,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 18,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 19,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Macul",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 20,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 1,
    bedRooms: 1,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 21,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 1,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 22,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 1,
    bedRooms: 3,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 23,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 1,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 24,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 25,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 1,
    bedRooms: 4,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 26,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 27,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 3,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 28,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 2,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 29,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 30,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 31,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 6,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 32,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 33,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 34,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 35,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 36,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 37,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 38,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 39,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Las Condes",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },

  {
    idApartment: 40,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 1,
    bedRooms: 1,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 41,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 1,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 42,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 1,
    bedRooms: 3,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 43,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 1,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 44,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 45,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 1,
    bedRooms: 4,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 46,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 5,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 47,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 3,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 48,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 2,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 49,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 50,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 51,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 6,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 52,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 53,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 54,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 55,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 56,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage2,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 6,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 57,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage3,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 3,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 58,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage4,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
  {
    idApartment: 59,
    title: "Juan Mitjans 105",
    imagenPrincipal:productImage5,
    imgs: [productImage,productImage],
    comuna: "Providencia",
    bathRoom: 4,
    bedRooms: 2,
    dimentions: '200 mt2',
    parking: 1,
    price:'200.000',
    priceCommonExpenses: '100.000',
    video:'link yt',
    map:{lat:'',long:''},
    description:'',
    other:['cosina linda','caño en living'],
    createdAt:'20/07/2021'
  },
];
